# Generated by Django 3.0.7 on 2020-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0003_auto_20200607_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
